// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACol: typeof import('@arco-design/web-vue')['Col']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AOption: typeof import('@arco-design/web-vue')['Option']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASkeleton: typeof import('@arco-design/web-vue')['Skeleton']
    ASkeletonLine: typeof import('@arco-design/web-vue')['SkeletonLine']
    ASkeletonShape: typeof import('@arco-design/web-vue')['SkeletonShape']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    Header: typeof import('./components/Header.vue')['default']
    IconGithub: typeof import('@arco-design/web-vue/es/icon')['IconGithub']
    IconMoonFill: typeof import('@arco-design/web-vue/es/icon')['IconMoonFill']
    IconShareAlt: typeof import('@arco-design/web-vue/es/icon')['IconShareAlt']
    IconSunFill: typeof import('@arco-design/web-vue/es/icon')['IconSunFill']
    LayoutSkeleton: typeof import('./components/LayoutSkeleton.vue')['default']
  }
}

export {}
