/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ALink: typeof import('@arco-design/web-vue')['Link']
    AOption: typeof import('@arco-design/web-vue')['Option']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    Header: typeof import('./components/Header.vue')['default']
    IconGithub: typeof import('@arco-design/web-vue/es/icon')['IconGithub']
    IconMoonFill: typeof import('@arco-design/web-vue/es/icon')['IconMoonFill']
    IconShareAlt: typeof import('@arco-design/web-vue/es/icon')['IconShareAlt']
    IconSunFill: typeof import('@arco-design/web-vue/es/icon')['IconSunFill']
  }
}
